{
 "title": "Substrate Node Template Metrics",
 "description": "Grafana dashboard for substrate template metrics. Instructions on use: https://substrate.dev/docs/en/tutorials/visualize-node-metrics/",
 "tags": [
  "substrate",
  "blockchain",
  "node",
  "template"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Block Height (best)",
   "type": "stat",
   "description": "What your node sees as the highest block (NOT finalized)",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"best\"}",
     "legendFormat": "Height(best)"
    }
   ]
  },
  {
   "title": "Block Height (finalized)",
   "type": "stat",
   "description": "What your node sees as the highest finalized block ( less than or equal to best)",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"finalized\"}",
     "legendFormat": "Height(finalized)"
    }
   ]
  },
  {
   "title": "Block Total Tx",
   "type": "stat",
   "description": "Total transactions in best block",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_proposer_number_of_transactions",
     "legendFormat": "Height(best)"
    }
   ]
  },
  {
   "title": "State Cashe (bytes)",
   "type": "stat",
   "description": "What your node sees as the highest finalized block ( less than or equal to best)",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "substrate_state_cache_bytes", "legendFormat": "Size (bytes)" }
   ]
  },
  {
   "title": "LibP2P peers",
   "type": "timeseries",
   "description": "Number of connected peers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count",
     "legendFormat": "Number of network gossip peers"
    }
   ]
  },
  {
   "title": "Proposer Block Construction Time",
   "type": "timeseries",
   "description": "histogram 90th quantiles for time to construct a block (seconds) More info: https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(substrate_proposer_block_constructed_bucket[5m])) by (le))",
     "legendFormat": "90th quantile for block construction time (s)"
    }
   ]
  }
 ]
}