{
 "title": "Lava Provider",
 "tags": [
  "RPC",
  "Provider"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "instance", "label": "Lavap instance IP", "query": "142.132.209.60:7780" }
  ]
 },
 "panels": [
  { "title": "Provider Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Provider Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "provider_frozen", "legendFormat": "{{chain}}" }
   ]
  },
  {
   "title": "Block Update Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(spec) (sum by(spec) (rate(lava_provider_last_serviced_block_update_time_seconds{instance=\"$instance\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QoS Availability",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(spec) (lava_consumer_QoS{qos_metric=\"availability\", instance=\"$instance\"})",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "QoS Latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(spec) (lava_consumer_QoS{qos_metric=\"latency\", instance=\"$instance\"})",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "QoS Sync",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(spec) (lava_consumer_QoS{qos_metric=\"sync/freshness\", instance=\"$instance\"})",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "Errors in last 24h",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(spec) (increase(lava_provider_total_errored{instance=\"$instance\"}[24h]))",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "CU Statistics",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(spec) (lava_provider_total_relays_serviced{instance=\"$instance\"})",
     "legendFormat": "{{spec}}"
    },
    {
     "expr": "sum by(spec) (lava_provider_total_cu_serviced{instance=\"$instance\"})",
     "legendFormat": "{{spec}}"
    },
    {
     "expr": "sum by(spec) (lava_provider_total_cu_paid{instance=\"$instance\"})",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "Total requests in last 24h",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(apiInterface) (increase(lava_provider_total_cu_serviced{instance=\"$instance\"}[24h]))",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "Errors in Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": "sum(lava_provider_total_errored{instance=\"$instance\"})",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  { "title": "Active nodes rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "EVMOS RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(apiInterface) (rate(lava_provider_total_cu_serviced{spec=\"EVMOS\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "EVMOS RATE PEAK",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(apiInterface) (rate(lava_provider_total_cu_serviced{spec=\"EVMOS\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "EVMOST RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(apiInterface) (rate(lava_provider_total_cu_serviced{spec=\"EVMOST\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "EVMOST RATE PEAK",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(apiInterface) (rate(lava_provider_total_cu_serviced{spec=\"EVMOST\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "AXELAR RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(lava_provider_total_cu_serviced{spec=\"AXELAR\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "AXELAR RATE PEAK",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(apiInterface) (rate(lava_provider_total_cu_serviced{spec=\"AXELAR\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "AXELART RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "rate(lava_provider_total_cu_serviced{spec=\"AXELART\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "AXELART RATE PEAK",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(apiInterface) (rate(lava_provider_total_cu_serviced{spec=\"AXELART\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "AGR RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(apiInterface) (rate(lava_provider_total_cu_serviced{spec=\"AGR\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "AGR RATE PEAK",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(apiInterface) (rate(lava_provider_total_cu_serviced{spec=\"AGR\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "AGRT RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(apiInterface) (rate(lava_provider_total_cu_serviced{spec=\"AGRT\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "AGRT RATE PEAK",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(apiInterface) (rate(lava_provider_total_cu_serviced{spec=\"AGRT\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "NEAR RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(lava_provider_total_cu_serviced{spec=\"NEAR\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "NEAR RATE PEAK",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(apiInterface) (rate(lava_provider_total_cu_serviced{spec=\"NEAR\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "NEART RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "rate(lava_provider_total_cu_serviced{spec=\"NEART\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "NEART RATE PEAK",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(apiInterface) (rate(lava_provider_total_cu_serviced{spec=\"NEART\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  { "title": "Block Sync Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "AGR Block Height Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "lava_latest_block{spec=\"AGR\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "AGR Block Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lava_latest_block{spec=\"AGR\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "AGRT Block Height Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "lava_latest_block{spec=\"AGRT\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "AGRT Block Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lava_latest_block{spec=\"AGRT\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "EVMOS Block Height Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "lava_latest_block{spec=\"EVMOS\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "EVMOS Block Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lava_latest_block{spec=\"EVMOS\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "EVMOST Block Height Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "lava_latest_block{spec=\"EVMOST\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "EVMOST Block Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lava_latest_block{spec=\"EVMOST\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "AXELAR Block Height Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "lava_latest_block{spec=\"AXELAR\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "AXELAR Block Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lava_latest_block{spec=\"AXELAR\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "AXELART Block Height Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "lava_latest_block{spec=\"AXELART\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "AXELART Block Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lava_latest_block{spec=\"AXELART\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "NEAR Block Height Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "lava_latest_block{spec=\"NEAR\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "NEAR Block Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lava_latest_block{spec=\"NEAR\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "NEART Block Height Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "lava_latest_block{spec=\"NEART\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "NEART Block Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lava_latest_block{spec=\"NEART\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  }
 ]
}